language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.2
  - 2.11.11

script:
  - bash scripts/build.sh $TEST_SUITE $ACTION $AND

addons:
  postgresql: "9.3"
  mysql: "5.7"
  apt:
    packages:
    - postgresql-9.3-postgis-2.3

after_success:
  - if [ "$TRAVIS_SCALA_VERSION" = "2.12.2" ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e7f5152049eff61e3376
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
